Repository Sitecore/Sitecore-Migration-Game, pull requests merged in 2023-09, with the labels that each got.

#91 90 add community articles
  src/components/Outcomes/OutcomeGenerator/OutcomeGenerator.tsx
  src/lib/GameContextParser.ts
  src/models/OutcomeConditions.ts
Labels: enhancement

#98 97 add product recommendation reasons
  cypress/e2e/OutcomeFlow/outcome.cy.ts
  src/GraphQL/Queries/Outcome.gql
  src/components/Outcomes/OutcomeGenerator/OutcomeGenerator.tsx
  src/models/IOutcome.ts
  src/models/IOutcomeReason.ts
  src/models/index.ts
Labels: enhancement

#99 Changed jasonstcyr.com to versions on community.sitecore.com
  src/components/Outcomes/OutcomeGenerator/OutcomeGenerator.tsx
Labels: documentation

#87 Replace tooltips on mobile with popover
  public/fantasy/icon-button-active.svg
  src/chakra/theme/fantasy/button.ts
  src/chakra/theme/fantasy/card.ts
  src/components/Prompts/ButtonGroup/ButtonGroup.tsx
  src/components/Prompts/MultiSelect/MultiSelect.tsx
Labels: enhancement, help wanted
